AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fuzzbun-api

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  SeriesSearchFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: seriessearch/
      Handler: main
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /seriessearch
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  FuzzbunAPI:
    Description: "API endpoints for Fuzzbun"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/seriessearch/"
  SeriesSearchFunction:
    Description: "Series Search Function ARN"
    Value: !GetAtt SeriesSearchFunction.Arn
  SeriesSearchFunctionIamRole:
    Description: "Implicit IAM Role created for Series Search function"
    Value: !GetAtt SeriesSearchFunctionRole.Arn
